name: rentify
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-85.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
    # bloc
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  #route
  auto_route: ^7.8.2
  # database
  hive_flutter: ^1.1.0
  #theme
  google_fonts: ^5.1.0
  flavor: ^2.0.0
  
  intl: ^0.18.0

  flutter_localizations:
    sdk: flutter
  package_info_plus: ^4.1.0
#  image_picker: ^1.0.4
  flutter_gen: ^5.3.1
  firebase_core: ^2.16.0
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.11.1
  flutter_localization: ^0.1.14
  localization: ^2.1.0
  firebase_crashlytics: ^3.4.3
  uuid: ^4.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/svg/
    - assets/icons/png/
    - assets/images/svg/
    - assets/images/png/
