name: rentify
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-85.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9

  # state management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  #route
  auto_route: ^7.8.4

  # localDB
  hive_flutter: ^1.1.0

  #theme
  google_fonts: ^6.1.0

  #flavor
  flavor: ^2.0.0

  #localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1


  flutter_localization: ^0.1.14
  localization: ^2.1.0
  
  #Obtain package information of the device
  package_info_plus: ^4.2.0

  #image
  image_picker: ^1.0.4

  #Assets generator
  flutter_gen: ^5.3.2

  #firebase, database
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1



  firebase_crashlytics: ^3.4.3
  uuid: ^4.2.1

  #for freezed
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_messaging: ^14.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #Code generation
  build_runner: ^2.4.6
  freezed: ^2.4.3
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.2
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/svg/
    - assets/icons/png/
    - assets/images/svg/
    - assets/images/png/
